# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
    
      - name: send default message to mura
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.ABLETON_BOT_MURA }}
          token: ${{ secrets.ABLETON_BOT_TOKEN }}
          message: |
            Yo, ${{github.event.pusher.name}} pushed new commits 
            <pre>${{ join(github.event.commits.*.message, '\n')}}</pre>
          
      - name: send default message to gala
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.ABLETON_BOT_GALA }}
          token: ${{ secrets.ABLETON_BOT_TOKEN }}
          message: |
            Yo, ${{github.event.pusher.name}} pushed new commits 
            <pre>${{ join(github.event.commits.*.message, '\n')}}</pre>
          
          
          
